# Generated by Django 4.2.16 on 2024-09-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='duration',
            field=models.IntegerField(default=30, help_text='Duración en segundos'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='file',
            field=models.FileField(upload_to='ads/%Y/%m/%d/'),
        ),
    ]
