# Generated by Django 4.2.16 on 2024-09-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_duration_alter_ad_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='duration',
            field=models.IntegerField(default=10, help_text='Duración en segundos'),
        ),
    ]
